config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  use_doorkeeper
  devise_for :authors, except: [:destroy]
  root "pages#home"

  devise_scope :author do
    get '/authors/sign_out' => 'devise/sessions#destroy', as: 'destroy_authsession'
  end

  #article routes
  resources :articles, except: [:destroy] do
    resources :comments, except: :destroy
  end
  delete 'articles/:id/delete' => 'articles#destroy', as: 'articles_delete'
  get '/articles/:id/delete' => 'articles#destroy'
  delete '/articles/:article_id/comment/delete' => 'comments#destroy', as: 'delete_comment'
  post '/articles/:article_id/like' => 'likes#create', as: 'like'
  get '/search' => 'articles#search', as: 'search'

  # user routes
  get 'signup' => 'users#new'
  resources :users, except: [:new, :destroy] 

  delete '/users/:id/delete' => 'users#destroy', as: 'delete_user'
  get '/users/:id/delete' => 'users#destroy'

  #savedarticles routes
  get '/articles/:article_id/savedarticles/new' => 'savedarticles#create', as: 'savearticle'
  delete '/articles/:article_id/removesaved' => 'savedarticles#destroy', as: 'removefromsaved'
  get '/author/:author_id/savedarticles' => 'savedarticles#index', as: 'savedarticles'
  get '/articles/:article_id/removesaved' => 'savedarticles#destroy'

  #api routes
  use_doorkeeper
    namespace :api do
      namespace :v1 do
        resources :authors 
      end
    end
  get '/api/v1/articles' => 'api/v1/articles#all_articles'
  get '/api/v1/articles/:id' => 'api/v1/articles#show',as: "api_v1_article"
  post '/api/v1/articles/new' => 'api/v1/articles#create',as: "api_create_article"
  get '/api/v1/authors/:id/articles' => 'api/v1/articles#index',as: "user_articles"

  #doorkeeper routes

    use_doorkeeper do
      skip_controllers :authorizations, :applications, :authorized_applications
    end

end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :author
    has_many :comments, dependent: :delete_all
    has_many :likes, dependent: :delete_all
    has_many :views, dependent: :delete_all

    has_rich_text :body
    validates :body , presence: true, length: {minimum: 400}

    has_many :article_categories,dependent: :delete_all
    has_many :categories, through: :article_categories

    validates :title , presence: true,uniqueness: true, length: {minimum: 6, maximum: 80}
    validates :description, presence: true, length: {minimum: 15, maximum: 600}

    scope :filter_by_title, -> (title) {where("lower(title) LIKE :search", search: "%#{title.downcase}%")}

    def self.filter_by_category(category)
        cg = Category.where(name: category)
        articles = cg.map{ |cat| cat.articles}
        articles = articles.flatten
        return articles
    end

    def already_saved(current_author)
        articles = current_author.savedarticles
        #articles = articles.map{ |obj| obj.article_id }
        articles = articles.pluck(:article_id)
        return articles.include?(self.id)
    end

    def already_viewed(current_author)
        views = self.views
        views = views.pluck(:author_id)
        return views.include?(current_author.id)
    end
end

require 'uri'
require 'net/http'
require "net/https"
require 'openssl'
require "json"
module Content
    class CheckContent
        def initialize
            @content = ""
        end
        def is_abusive(content)
            @content = content.to_plain_text.to_s
            @content = @content.gsub(/[[:^ascii:]]/, "")
            api = "https://neutrinoapi.net/bad-word-filter?user-id=InbaKrish&api-key=JWwEyBi3ht8YGNDM6HMDvV06BEvEcsZlkQKBwyswN6k3rK6S&content="+@content
            url = URI(api)

            http = Net::HTTP.new(url.host, url.port)
            http.use_ssl = true
            http.verify_mode = OpenSSL::SSL::VERIFY_NONE
            request = Net::HTTP::Post.new(url)
            response = http.request(request)
            if response.kind_of? Net::HTTPSuccess
                response = JSON.parse response.body
                puts response
                return response["bad-words-list"].join(',')
            end
            return false
        end
    end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
    before_action :set_article, only: [ :show]
    protect_from_forgery with: :null_session
    before_action :doorkeeper_authorize!
    before_action :current_author, only: [:create]

    def all_articles
        @articles = Article.all
        render json: @articles ,except: [:created_at,:updated_at]
    end
    #user's articles
    def index
        @author = Author.find(params[:id])
        @articles = @author.articles
        render json: @articles, except: [:created_at,:updated_at]
    end

    def show
        body = @article.body.body.to_plain_text
        render :json => @article.as_json(except: [:created_at,:updated_at]).merge(:body => body)
    end
    #create
    def create
        @article = Article.new(article_params)
        @article.author_id = current_author.id
        if @article.save
            render json: @article,except: [:created_at,:updated_at]
        else
            render json: @article.errors
        end
    end
    
    private
    def current_author
        Author.find(doorkeeper_token.resource_owner_id)
    end

    def article_params
        params.permit(:title,:description,:body)
    end

    def set_article
        @article = Article.find(params[:id])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_author! , except: [:show, :index]
    before_action :check_user , only: [:edit, :update, :destroy]
    @@abuse_limit = 0
    def show
        if current_author
           if not @article.already_viewed(current_author)
            view = @article.views.new(author_id:current_author.id)
            view.save
            redirect_to article_path(@article)
           end
        end

        respond_to do |format|
            format.html
            format.pdf do
              render pdf: "#{@article.title}-by #{@article.author.username}-PDF", template: "articles/articlepdf.html.erb",
                 layout: 'pdf.html'
            end
        end
    end
    def index
        @articles = Article.all.order(updated_at: :desc).includes(:author,:categories)
        @articles = @articles.filter_by_title(params[:search]) if params[:search].present?
        @articles = @articles.filter_by_category(params[:category][:name]) if params[:category].present? and params[:category][:name].present?
        #@all_articles = Article.all
        respond_to do |format|
            format.html
            format.csv { send_data Services::Conversion.new.to_csv, filename: "articles-#{Date.today}.csv" }
        end
    end
    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.author_id = current_author.id
        bad_words = Content::CheckContent.new.is_abusive(@article.body)
        if bad_words.length > 0 
            flash[:notice] = "Your content is abusive , try to remove - #{bad_words} words"
            @@abuse_limit = @@abuse_limit + 1
            if @@abuse_limit > 3
                flash[:notice] = "Your account is banned due to abusive content , contact admin !!!"
                current_author.lock_access!
                @@abuse_limit = 0
                redirect_to new_author_session_path
                return
            end
            render :edit
        else
            if @article.save
                flash[:notice] = "Article created successfully"
                redirect_to @article
            else
                render :new
            end
        end
    end

    def update
        bad_words = Content::CheckContent.new.is_abusive(@article.body)
        if bad_words.length > 0 
            flash[:notice] = "Your content is abusive , try to remove - #{bad_words} words"
            @@abuse_limit = @@abuse_limit + 1
            if @@abuse_limit > 3
                flash[:notice] = "Your account is banned due to abusive content , contact admin !!!"
                current_author.lock_access!
                @@abuse_limit = 0
                redirect_to new_author_session_path
                return
            end
            render :edit
        else
            if @article.update(article_params)
                flash[:notice] = "Article updated successfully"
                redirect_to @article
            else
                render :edit
            end
        end
    end

    def destroy
        saved_articles = Savedarticle.where("article_id = ?",@article.id)
        saved_articles.delete_all()
        @article.destroy()
        redirect_to articles_path
    end

    private

    def article_params
        params.require(:article).permit(:title,:description,:body,category_ids: [] )
    end

    def set_article
        @article = Article.find(params[:id])
    end

    def check_user
        if current_author != @article.author
            flash[:alert] = "You are not the owner of this Article !!!"
            redirect_to articles_path
        end
        return true
    end
end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/views/articles/_addcomment.html.erb
<div class="container bot-space">
<%= form_with(model: [@article,@article.comments.build], local: true, class:"form-group") do |new| %>
    <%= new.text_field :content, class:"form-control shadow rounded" %> <br>
     <center> <%= new.submit "POST", class:"btn btn-outline-secondary btn-sm shadow rounded" %> </center>
<%end%>
</div>
<div>

app/views/articles/_comments.html.erb
<div class="container bot-space">
<% @article.comments.each do |cmt| %>
        <div class="well "> 
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -> 
         "<%= cmt.content %>" <br>&nbsp;&nbsp;
        <small> by @<i> <%= Author.find(cmt.user_id).username %><i></small> 
        <% if current_author and cmt.user_id == current_author.id %>&nbsp;&nbsp;&nbsp;
           <small><%= link_to "Remove", delete_comment_path(article_id: @article.id),method: :delete,
                class:"text-danger" %> </small>
        <%end%>
        <br></div> <br>

<%end%> 
<div>

app/views/articles/_form.html.erb
<div class="container ">

<%= render 'shared/errors', cur_obj:@article %>

<%= form_with(model: @article, local: true, class:"shadow-lg p-3 mb-3 rounded") do |new| %>
    
    <span style="color:rgb(179, 179, 179)"> 
    <div class="form-group row mt-4">
       <%= new.label :title, class:"col-2 col-form-table" %>
        <div class="col-10">
        <%= new.text_field :title, class:"form-control shadow rounded", placeholder:"Title of the article" %></div>
    </div></span>
    
    <span style="color:rgb(179, 179, 179)">
    <div class="form-group row mt-4">
        <%= new.label :description, class:"col-2 col-form-table" %>
        <div class="col-10">
        <%= new.text_area :description, class:"form-control shadow rounded", placeholder:"Description of the article", rows:3 %></div>
    </div></span>

    <span style="color:rgb(179, 179, 179)">
    <div class="form-group row mt-4">
        <%= new.label :body, class:"col-2 col-form-table" %>
        <div class="col-10">
        <%= new.rich_text_area :body,class:"form-control shadow rounded",rows:12 %></div>
    </div></span><hr>
    <span style="color:rgb(179, 179, 179)">
    &nbsp;&nbsp;&nbsp;&nbsp;
    <%= "Choose the categories (can be multiple or can be empty )"%>
    <div class="form-group row mt-4">
        <%= new.label :category, class:"col-2 col-form-table" %>
        <div class="col-10 text-white">
            <%= new.collection_check_boxes :category_ids, Category.all, :id, :name do |cg| %>
                <%= cg.label(class: "form-check-label") {cg.check_box(class: "form-check-input shadow") +"  "+ cg.text  } %>
                <%= "  " %>
            <% end %>
    </div></span>
    <br><br><br>
       <center> <%= new.submit class:"btn btn-outline-light btn-lg shadow rounded" %> </center>
    <br><br>
    
    <h6><%= link_to '< Cancel and return to -> Articles page >', articles_path,class:"text-success" %></h6>
<%end%>
</div>

app/views/articles/_links.html.erb
<center>
<%= article.views.count %> <%= (article.views.count) == 1 ? 'View' : 'Views'%> <br>
<%= article.likes.count %> <%= (article.likes.count) == 1 ? 'Like' : 'Likes'%>
<%if current_author%>
<%= link_to(image_tag("https://image.flaticon.com/icons/png/512/725/725111.png",
    class: 'image-responsive'), 
    like_path(article_id: article.id), method: :post )%>
&nbsp;
    <% if article.already_saved(current_author) %>
        <%= "|  Unsave"%>
        <%= link_to(image_tag("https://image.flaticon.com/icons/png/512/709/709631.png",
    class: 'image-responsive'),
        removefromsaved_path(:article_id => article.id), method: :delete) %> 
    <% else %>
        <%= "|  Save"%>
        <%= link_to(image_tag("https://image.flaticon.com/icons/png/512/709/709496.png",
    class: 'image-responsive'), 
        savearticle_path(:article_id => article.id)) %>
    <% end %>
<%end%>
</center>  

app/views/articles/_showarticles.html.erb
<center>
<% if current_page?(articles_path) %>
    <%= form_tag( articles_path , method: :get) do %>
        <div class="form-inline mt-1 ">
            <%= text_field_tag :search, params[:search], placeholder: " Search Articles", class:"form-comtrol shadow rounded col-4" %>
            <%= collection_select(:category, :name, Category.all,:name,:name,{:prompt => 'Categories'},{class:"form-comtrol shadow rounded col-1 "}) %>
            &nbsp;<%= submit_tag "Search", class:"btn btn-info btn-sm shadow rounded", :name => nil %>
        </div>
    <% end %>
<%end%>
</center>
<%if @articles.any?%>
<% @articles.each do |cur_article| %>
            <br><br>
            <div class="col-6">
        <div class="card text-center shadow-lg p-3 mb-5 rounded text-muted bg-dark">
            <div class="card-header text-white">
               <i> by @<%= link_to cur_article.author.username, user_path(cur_article.author.id), class:"text-secondary" %> </i> 
               
            </div>
            <div class="card-body">
                <h5 class="card-title "> <%= link_to cur_article.title, article_path(cur_article), class:"text-info" %> </h5>

                <% if cur_article.categories.any? %>
                    <div class="mt-2"><%= render cur_article.categories %></div> 
                <%end%>

                <%= render 'articles/links', article: cur_article %>
                <p class="card-text"> 
                <%= truncate(cur_article.description,length:120) %> </p>
                
                <% if current_author && current_author == cur_article.author %>
                <%= link_to "Edit", edit_article_path(cur_article) ,class:"btn btn-outline-warning"%>&nbsp;&nbsp;
                <%=  link_to 'Delete', articles_delete_path(cur_article), confirm: "Are you sure to delete?" ,class:"btn btn-outline-danger", method: :delete%>
                <%end%>
            </div>
            
            <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(cur_article.created_at)%> ago ,
                Updated <%= time_ago_in_words(cur_article.updated_at)%> ago
                </small>
            </div>
            </div></div></div>
        <% end %>
<%else%>
    <br><br><br><br><br><br><br><br> <center>
    <h1 class="text-muted"> No articles available</h1> </center>
<%end%>

app/views/articles/articlepdf.html.erb
<div class="container">
    <div >
        <p><h1><%= @article.title %></h1><small><i>by @<%= @article.author.username %></i></small></p>
        <pre style="font-size:15px">
            <%= @article.body %>
        <pre>
    </div>
</div>

app/views/articles/edit.html.erb
<center>
    <h1 class="mt-4 "> <span style="color:rgb(179, 179, 179)">Edit the Article</span></h1><br>
    <%= render 'form' %>
</center>

app/views/articles/index.html.erb
<center>
        <h1 class="mt-4 "> <span style="color:rgb(179, 179, 179)"> All Articles</span></h1>
        <% if current_author %>
        <%= link_to('Export articles - CSV', articles_path(@article, format: :csv), class:"btn btn-success btn-sm shadow rounded mb-3",target: :_blank) %>
        <%end%>
        <%= render 'showarticles' %>
</center>

app/views/articles/new.html.erb
<center>
    <h1 class="mt-4 "> <span style="color:rgb(179, 179, 179)">Create New Article</span></h1><br>
    <%= render 'form' %>    
</center>

app/views/articles/show.html.erb
<div class="container">
    <p>
        <%= link_to '<< Return Home', articles_path, class:"btn btn-outline-secondary btn-sm shadow rounded" %> &nbsp;
        <%if current_author%>
            <% if @article.already_saved(current_author) %>
                <%= link_to 'Remove from saved',removefromsaved_path(:article_id => @article.id), method: :delete, class:"btn btn-outline-danger btn-sm shadow rounded" %> 
            <% else %>
                <%= link_to 'Save_article', savearticle_path(:article_id => @article.id), class:"btn btn-outline-muted btn-sm shadow rounded text-muted" %>
            <% end %>
            <%= link_to('PDF', article_path(@article, format: :pdf), class:"btn btn-danger btn-sm shadow rounded text-white",target: :_blank) %> 
        <%end%>&nbsp;
    </p>
    <div class="text-white">
        <p><h2><%= @article.title %></h2><small><i>by @<%= link_to @article.author.username, user_path(@article.author.id), class:"text-secondary" %></i></small></p>
        <pre class="text-white">
            <%= @article.body %>
        <pre>
    </div>
    <h2> <%= @article.comments.count %> Comments</h2>
    <%= render "comments" %>
    <%  if current_author %>
        <h5>Add your comment </h5>
        <%= render "addcomment" %>
    <%end%>
</div>