config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  use_doorkeeper
  devise_for :authors, except: [:destroy]
  root "pages#home"

  devise_scope :author do
    get '/authors/sign_out' => 'devise/sessions#destroy', as: 'destroy_authsession'
  end

  #article routes
  resources :articles, except: [:destroy] do
    resources :comments, except: :destroy
  end
  delete 'articles/:id/delete' => 'articles#destroy', as: 'articles_delete'
  get '/articles/:id/delete' => 'articles#destroy'
  delete '/articles/:article_id/comment/delete' => 'comments#destroy', as: 'delete_comment'
  post '/articles/:article_id/like' => 'likes#create', as: 'like'
  get '/search' => 'articles#search', as: 'search'

  # user routes
  get 'signup' => 'users#new'
  resources :users, except: [:new, :destroy] 

  delete '/users/:id/delete' => 'users#destroy', as: 'delete_user'
  get '/users/:id/delete' => 'users#destroy'

  #savedarticles routes
  get '/articles/:article_id/savedarticles/new' => 'savedarticles#create', as: 'savearticle'
  delete '/articles/:article_id/removesaved' => 'savedarticles#destroy', as: 'removefromsaved'
  get '/author/:author_id/savedarticles' => 'savedarticles#index', as: 'savedarticles'
  get '/articles/:article_id/removesaved' => 'savedarticles#destroy'

  #api routes
  use_doorkeeper
    namespace :api do
      namespace :v1 do
        resources :authors 
      end
    end
  get '/api/v1/articles' => 'api/v1/articles#all_articles'
  get '/api/v1/articles/:id' => 'api/v1/articles#show',as: "api_v1_article"
  post '/api/v1/articles/new' => 'api/v1/articles#create',as: "api_create_article"
  get '/api/v1/authors/:id/articles' => 'api/v1/articles#index',as: "user_articles"

  #doorkeeper routes

    use_doorkeeper do
      skip_controllers :authorizations, :applications, :authorized_applications
    end

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    #has_many :articles, dependent: :destroy
    #has_many :savedarticles, dependent: :delete_all
    validates :user_name, presence: true, uniqueness: { case_sensitive: false },  length: {minimum: 3, maximum: 80}

    EMAIL_VALID_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false },  length: {minimum: 3, maximum: 80},
                format: {with: EMAIL_VALID_REGEX, message: "Provied Valid email address"}

    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]
    before_action :author_signed_in?  , only: [:edit, :update ]
    before_action :authenticate_author!, only: [:edit, :update, :destroy ]

    def show
        @articles = @user.articles
    end

    def index
        @users = Author.all
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "#{@user.user_name} details updated successfully..."
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def destroy
        @user_comments = Comment.where("user_id = ?",@user.id)
        @user_comments.delete_all
        @user.destroy
        flash[:alert] = "Your profile and Your Articles DESTROYED , Successfully !!!"
        redirect_to root_path
    end


    private
    def set_user
        @user = Author.find(params[:id])
    end
    def user_params
        params.require(:user).permit(:user_name,:email,:password)
    end
    def check_cur_user
        if cur_user != @user
            flash[:alert] = "You are not the owner of this Profile !!!"
            redirect_to user_path(@user)
        end
    end
end

app/views/users/_form.html.erb
<div class="container ">

<%= render 'shared/errors', cur_obj:@user %>

<%= form_with(model: @user, local: true, class:"shadow-lg p-3 mb-3 rounded") do |new| %>
    
    <span style="color:rgb(179, 179, 179)"> 
    <div class="form-group row mt-4">
       <%= new.label :user_name, class:"col-2 col-form-table" %>
        <div class="col-10">
        <%= new.text_field :user_name, class:"form-control shadow rounded", placeholder:"User name" %></div>
    </div></span>
    
    <span style="color:rgb(179, 179, 179)">
    <div class="form-group row mt-4">
        <%= new.label :email, class:"col-2 col-form-table" %>
        <div class="col-10">
        <%= new.email_field :email, class:"form-control shadow rounded", placeholder:"User email address" %></div>
    </div></span>

    <span style="color:rgb(179, 179, 179)">
    <div class="form-group row mt-4">
        <%= new.label :password, class:"col-2 col-form-table" %>
        <div class="col-10">
        <%= new.password_field :password, class:"form-control shadow rounded", placeholder:"Enter a Password" %></div>
    </div></span>
    <br>
       <center> <%= new.submit(@user.new_record? ? "Sign Up" : "Update", class:"btn btn-outline-light btn-lg shadow rounded") %> </center>
    <br><br>
    
    <h6><%= link_to '< Cancel and return to -> Articles page >', articles_path,class:"text-success" %></h6>
<%end%>
</div>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
         <h1 class="mt-4 "> <span style="color:rgb(179, 179, 179)">Update user details</span></h1><br>
        <%= render 'form' %>
    </center>
</body>
</html>

app/views/users/index.html.erb
<center>
<div class="container mt-4">
<h1> <span style="color:rgb(179, 179, 179)"> All Authors</span></h1><br>
<% @users.each do |usr|%>
<div class="row justify-content-md-center">
        <div class="card text-muted bg-dark mb-5 col-6">
        <center><h5 class="card-header text-primary"><%= usr.username %>
            <%= link_to(image_tag("http://assets.stickpng.com/images/580b57fcd9996e24bc43c521.png", class: 'image-responsive'), 
                'https://www.instagram.com/', target: :_blank) %></center>  
        </h5>
            <div class="card-body">
                <h5 class="card-title"> *Author : <%= usr.username %></h5>
                <p class="card-text"><i>Author email : <%= usr.email %></i></p>
                <%= link_to "Go to Profile ", user_path(usr),class:"btn btn-outline-success"  %>
            </div>
    </div></div>
<%end%>
</div>
</center>

app/views/users/show.html.erb
<center>
    <h1 class="mt-4 "> <span style="color:rgb(179, 179, 179)"> <%=@user.username%>'s articles </span></h1><br>
    <% if current_author == @user%>
    <%= link_to "Saved Articles", savedarticles_path(author_id: current_author.id) ,class:"btn btn-outline-info" %> &nbsp;
    <%= link_to "Delete Profile", delete_user_path(author_id: current_author.id),method: :delete ,class:"btn btn-outline-danger" %>&nbsp;
    <%= link_to "Edit Profile", edit_author_registration_path(author_id: current_author.id),class:"btn btn-outline-warning" %>
    <%end%>
    <% if @articles.length > 0 %>
        <%= render 'articles/showarticles' %>
    <%else%>
        <br><br><br><br><br><br>
        <h1 style="color:rgb(115, 115, 115);">No Articles Available</h1>
    <%end%>
</center>