config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  use_doorkeeper
  devise_for :authors, except: [:destroy]
  root "pages#home"

  devise_scope :author do
    get '/authors/sign_out' => 'devise/sessions#destroy', as: 'destroy_authsession'
  end

  #article routes
  resources :articles, except: [:destroy] do
    resources :comments, except: :destroy
  end
  delete 'articles/:id/delete' => 'articles#destroy', as: 'articles_delete'
  get '/articles/:id/delete' => 'articles#destroy'
  delete '/articles/:article_id/comment/delete' => 'comments#destroy', as: 'delete_comment'
  post '/articles/:article_id/like' => 'likes#create', as: 'like'
  get '/search' => 'articles#search', as: 'search'

  # user routes
  get 'signup' => 'users#new'
  resources :users, except: [:new, :destroy] 

  delete '/users/:id/delete' => 'users#destroy', as: 'delete_user'
  get '/users/:id/delete' => 'users#destroy'

  #savedarticles routes
  get '/articles/:article_id/savedarticles/new' => 'savedarticles#create', as: 'savearticle'
  delete '/articles/:article_id/removesaved' => 'savedarticles#destroy', as: 'removefromsaved'
  get '/author/:author_id/savedarticles' => 'savedarticles#index', as: 'savedarticles'
  get '/articles/:article_id/removesaved' => 'savedarticles#destroy'

  #api routes
  use_doorkeeper
    namespace :api do
      namespace :v1 do
        resources :authors 
      end
    end
  get '/api/v1/articles' => 'api/v1/articles#all_articles'
  get '/api/v1/articles/:id' => 'api/v1/articles#show',as: "api_v1_article"
  post '/api/v1/articles/new' => 'api/v1/articles#create',as: "api_create_article"
  get '/api/v1/authors/:id/articles' => 'api/v1/articles#index',as: "user_articles"

  #doorkeeper routes

    use_doorkeeper do
      skip_controllers :authorizations, :applications, :authorized_applications
    end

end

app/views/layouts/_flash.html.erb
<div class="container mt-4 ml-6">

  <% flash.each do |name, msg| %>
    <div id="alert" class="alert alert-success alert-dismissible fade show" role="alert">
      <div style="text-align:left"> <%= msg %> </div>
    </div>
  <% end %>

  <script type="text/javascript">
    setTimeout(function () {
        $('#alert').alert('close');
    }, 2000);
  </script>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
&nbsp;&nbsp;&nbsp;
<%= link_to "Rails Blog", root_path ,class:"navbar-brand", id:"logo"  %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <%= link_to "Articles", articles_path,class:"nav-link "  %>
    </li>
    <li class="nav-item active">
        <%= link_to "Authors", users_path,class:"nav-link "  %>
    </li>

    <% if author_signed_in? %>
        <li class="nav-item">
            <%= link_to 'Logout', destroy_authsession_path,  class: "nav-link" %>
        </li>
        <li class="nav-item">
            <i><%= link_to "@"+current_author.username, user_path(current_author.id), class: "nav-link"%></i>
        </li>
    <%else%>
        <li class="nav-item">
            <%= link_to "Log In", new_author_session_path, class:"nav-link" %>
        </li>
    <%end%>
    </ul>
    <ul class="navbar-nav ms-auto ">
    <%if current_author%>
            <%= link_to 'New article',new_article_path, class:"btn btn-outline-success shadow rounded"  %> &nbsp;&nbsp;
            <%= link_to "Saved Articles", savedarticles_path(author_id: current_author.id) ,class:"btn btn-outline-info shadow rounded" %> &nbsp;&nbsp;
    <%end%>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <p><sub> <%= link_to '@inbasagaran', "https://www.linkedin.com/in/inbasagaran/", class:"text-secondary", target: :_blank %> </sub></p> &nbsp;&nbsp;&nbsp;
    </ul>
    
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body style="background-color:rgb(64, 64, 64)">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash'%>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title> <%= @article.title %> - PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>
  <div class='container'>
    <%= "PDF created at #{Time.zone.now} " %>
    <%= yield %>
  </div>
</body>
</html>